name: Test
on: [pull_request]

jobs:
  build:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        submodules: "true"

    - name: Set up Go 1.25
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
      with:
        go-version: 1.25

        # Caching seems to really slow down the build due to the time
        # taken to save the cache.
        cache: false
      id: go

    - name: Get dependencies
      run: |
        sudo apt-get install llvm

    - name: Build
      env:
        CGO_ENABLED: 0
      shell: bash
      run: |
        make full

    - name: StoreBuild
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
      with:
        name: tree-${{ matrix.os }}
        path: userspace/
